name: 5mins

on: 
  schedule:
   - cron: "*/3 * * * *"

     

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Echo time
      run: echo "time is $(date)"
