name: 5mins

on: 
  schedule:
   - cron: "*/5 * * * *"

     

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: echo "hey 5mins passed"